// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/proxy-server.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from proto/proxy-server.proto</summary>
public static partial class ProxyServerReflection {

  #region Descriptor
  /// <summary>File descriptor for proto/proxy-server.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ProxyServerReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Chhwcm90by9wcm94eS1zZXJ2ZXIucHJvdG8iwQEKDExvZ2luUmVxdWVzdBIM",
          "CgRuYW1lGAEgASgJEhAKCHByb3RvY29sGAIgASgNEhYKDm9ubGluZV9wbGF5",
          "ZXJzGAMgASgNEhMKC21heF9wbGF5ZXJzGAQgASgNEgwKBG1vdGQYBSABKAkS",
          "EAoIc29mdHdhcmUYBiABKAkSDAoEYXV0aBgHIAEoCBIOCgZzZWNyZXQYCCAB",
          "KAkSEAoIaXNfcHJveHkYCSABKAgSFAoMcHJvdG9jb2xfcmV2GAogASgFIqMB",
          "CgxBdXRoUmVzcG9uY2USEAoIcmVzcG9uY2UYASABKAUSDwoHbWVzc2FnZRgC",
          "IAEoCRIVCg1wcm94eV92ZXJzaW9uGAMgASgNEhkKEXByb3h5X3ZlcnNpb25f",
          "cmV2GAQgASgNEhAKCHByb3RvY29sGAUgASgNEh4KFnVzZV9wYWNrZXRfdHJh",
          "bnNsYXRpb24YBiABKAgSDAoEdHlwZRgHIAEoCSIXCgREYXRhEg8KB21lc3Nh",
          "Z2UYASABKAwiIgoPVm94ZWxTcnZNZXNzYWdlEg8KB21lc3NhZ2UYASABKAwi",
          "HAoKRGlzY29ubmVjdBIOCgZyZWFzb24YASABKAkiHwoMUHJveHlNZXNzYWdl",
          "Eg8KB21lc3NhZ2UYASABKAxiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::LoginRequest), global::LoginRequest.Parser, new[]{ "Name", "Protocol", "OnlinePlayers", "MaxPlayers", "Motd", "Software", "Auth", "Secret", "IsProxy", "ProtocolRev" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::AuthResponce), global::AuthResponce.Parser, new[]{ "Responce", "Message", "ProxyVersion", "ProxyVersionRev", "Protocol", "UsePacketTranslation", "Type" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Data), global::Data.Parser, new[]{ "Message" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::VoxelSrvMessage), global::VoxelSrvMessage.Parser, new[]{ "Message" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Disconnect), global::Disconnect.Parser, new[]{ "Reason" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ProxyMessage), global::ProxyMessage.Parser, new[]{ "Message" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class LoginRequest : pb::IMessage<LoginRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LoginRequest> _parser = new pb::MessageParser<LoginRequest>(() => new LoginRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<LoginRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProxyServerReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public LoginRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public LoginRequest(LoginRequest other) : this() {
    name_ = other.name_;
    protocol_ = other.protocol_;
    onlinePlayers_ = other.onlinePlayers_;
    maxPlayers_ = other.maxPlayers_;
    motd_ = other.motd_;
    software_ = other.software_;
    auth_ = other.auth_;
    secret_ = other.secret_;
    isProxy_ = other.isProxy_;
    protocolRev_ = other.protocolRev_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public LoginRequest Clone() {
    return new LoginRequest(this);
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 1;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "protocol" field.</summary>
  public const int ProtocolFieldNumber = 2;
  private uint protocol_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Protocol {
    get { return protocol_; }
    set {
      protocol_ = value;
    }
  }

  /// <summary>Field number for the "online_players" field.</summary>
  public const int OnlinePlayersFieldNumber = 3;
  private uint onlinePlayers_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint OnlinePlayers {
    get { return onlinePlayers_; }
    set {
      onlinePlayers_ = value;
    }
  }

  /// <summary>Field number for the "max_players" field.</summary>
  public const int MaxPlayersFieldNumber = 4;
  private uint maxPlayers_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint MaxPlayers {
    get { return maxPlayers_; }
    set {
      maxPlayers_ = value;
    }
  }

  /// <summary>Field number for the "motd" field.</summary>
  public const int MotdFieldNumber = 5;
  private string motd_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Motd {
    get { return motd_; }
    set {
      motd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "software" field.</summary>
  public const int SoftwareFieldNumber = 6;
  private string software_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Software {
    get { return software_; }
    set {
      software_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "auth" field.</summary>
  public const int AuthFieldNumber = 7;
  private bool auth_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Auth {
    get { return auth_; }
    set {
      auth_ = value;
    }
  }

  /// <summary>Field number for the "secret" field.</summary>
  public const int SecretFieldNumber = 8;
  private string secret_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Secret {
    get { return secret_; }
    set {
      secret_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "is_proxy" field.</summary>
  public const int IsProxyFieldNumber = 9;
  private bool isProxy_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool IsProxy {
    get { return isProxy_; }
    set {
      isProxy_ = value;
    }
  }

  /// <summary>Field number for the "protocol_rev" field.</summary>
  public const int ProtocolRevFieldNumber = 10;
  private int protocolRev_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int ProtocolRev {
    get { return protocolRev_; }
    set {
      protocolRev_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as LoginRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(LoginRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Name != other.Name) return false;
    if (Protocol != other.Protocol) return false;
    if (OnlinePlayers != other.OnlinePlayers) return false;
    if (MaxPlayers != other.MaxPlayers) return false;
    if (Motd != other.Motd) return false;
    if (Software != other.Software) return false;
    if (Auth != other.Auth) return false;
    if (Secret != other.Secret) return false;
    if (IsProxy != other.IsProxy) return false;
    if (ProtocolRev != other.ProtocolRev) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (Protocol != 0) hash ^= Protocol.GetHashCode();
    if (OnlinePlayers != 0) hash ^= OnlinePlayers.GetHashCode();
    if (MaxPlayers != 0) hash ^= MaxPlayers.GetHashCode();
    if (Motd.Length != 0) hash ^= Motd.GetHashCode();
    if (Software.Length != 0) hash ^= Software.GetHashCode();
    if (Auth != false) hash ^= Auth.GetHashCode();
    if (Secret.Length != 0) hash ^= Secret.GetHashCode();
    if (IsProxy != false) hash ^= IsProxy.GetHashCode();
    if (ProtocolRev != 0) hash ^= ProtocolRev.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (Protocol != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Protocol);
    }
    if (OnlinePlayers != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(OnlinePlayers);
    }
    if (MaxPlayers != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(MaxPlayers);
    }
    if (Motd.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Motd);
    }
    if (Software.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Software);
    }
    if (Auth != false) {
      output.WriteRawTag(56);
      output.WriteBool(Auth);
    }
    if (Secret.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(Secret);
    }
    if (IsProxy != false) {
      output.WriteRawTag(72);
      output.WriteBool(IsProxy);
    }
    if (ProtocolRev != 0) {
      output.WriteRawTag(80);
      output.WriteInt32(ProtocolRev);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (Protocol != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Protocol);
    }
    if (OnlinePlayers != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(OnlinePlayers);
    }
    if (MaxPlayers != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(MaxPlayers);
    }
    if (Motd.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Motd);
    }
    if (Software.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Software);
    }
    if (Auth != false) {
      output.WriteRawTag(56);
      output.WriteBool(Auth);
    }
    if (Secret.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(Secret);
    }
    if (IsProxy != false) {
      output.WriteRawTag(72);
      output.WriteBool(IsProxy);
    }
    if (ProtocolRev != 0) {
      output.WriteRawTag(80);
      output.WriteInt32(ProtocolRev);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (Protocol != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Protocol);
    }
    if (OnlinePlayers != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(OnlinePlayers);
    }
    if (MaxPlayers != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MaxPlayers);
    }
    if (Motd.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Motd);
    }
    if (Software.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Software);
    }
    if (Auth != false) {
      size += 1 + 1;
    }
    if (Secret.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Secret);
    }
    if (IsProxy != false) {
      size += 1 + 1;
    }
    if (ProtocolRev != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ProtocolRev);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(LoginRequest other) {
    if (other == null) {
      return;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.Protocol != 0) {
      Protocol = other.Protocol;
    }
    if (other.OnlinePlayers != 0) {
      OnlinePlayers = other.OnlinePlayers;
    }
    if (other.MaxPlayers != 0) {
      MaxPlayers = other.MaxPlayers;
    }
    if (other.Motd.Length != 0) {
      Motd = other.Motd;
    }
    if (other.Software.Length != 0) {
      Software = other.Software;
    }
    if (other.Auth != false) {
      Auth = other.Auth;
    }
    if (other.Secret.Length != 0) {
      Secret = other.Secret;
    }
    if (other.IsProxy != false) {
      IsProxy = other.IsProxy;
    }
    if (other.ProtocolRev != 0) {
      ProtocolRev = other.ProtocolRev;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 16: {
          Protocol = input.ReadUInt32();
          break;
        }
        case 24: {
          OnlinePlayers = input.ReadUInt32();
          break;
        }
        case 32: {
          MaxPlayers = input.ReadUInt32();
          break;
        }
        case 42: {
          Motd = input.ReadString();
          break;
        }
        case 50: {
          Software = input.ReadString();
          break;
        }
        case 56: {
          Auth = input.ReadBool();
          break;
        }
        case 66: {
          Secret = input.ReadString();
          break;
        }
        case 72: {
          IsProxy = input.ReadBool();
          break;
        }
        case 80: {
          ProtocolRev = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 16: {
          Protocol = input.ReadUInt32();
          break;
        }
        case 24: {
          OnlinePlayers = input.ReadUInt32();
          break;
        }
        case 32: {
          MaxPlayers = input.ReadUInt32();
          break;
        }
        case 42: {
          Motd = input.ReadString();
          break;
        }
        case 50: {
          Software = input.ReadString();
          break;
        }
        case 56: {
          Auth = input.ReadBool();
          break;
        }
        case 66: {
          Secret = input.ReadString();
          break;
        }
        case 72: {
          IsProxy = input.ReadBool();
          break;
        }
        case 80: {
          ProtocolRev = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class AuthResponce : pb::IMessage<AuthResponce>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AuthResponce> _parser = new pb::MessageParser<AuthResponce>(() => new AuthResponce());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<AuthResponce> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProxyServerReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public AuthResponce() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public AuthResponce(AuthResponce other) : this() {
    responce_ = other.responce_;
    message_ = other.message_;
    proxyVersion_ = other.proxyVersion_;
    proxyVersionRev_ = other.proxyVersionRev_;
    protocol_ = other.protocol_;
    usePacketTranslation_ = other.usePacketTranslation_;
    type_ = other.type_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public AuthResponce Clone() {
    return new AuthResponce(this);
  }

  /// <summary>Field number for the "responce" field.</summary>
  public const int ResponceFieldNumber = 1;
  private int responce_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Responce {
    get { return responce_; }
    set {
      responce_ = value;
    }
  }

  /// <summary>Field number for the "message" field.</summary>
  public const int MessageFieldNumber = 2;
  private string message_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Message {
    get { return message_; }
    set {
      message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "proxy_version" field.</summary>
  public const int ProxyVersionFieldNumber = 3;
  private uint proxyVersion_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint ProxyVersion {
    get { return proxyVersion_; }
    set {
      proxyVersion_ = value;
    }
  }

  /// <summary>Field number for the "proxy_version_rev" field.</summary>
  public const int ProxyVersionRevFieldNumber = 4;
  private uint proxyVersionRev_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint ProxyVersionRev {
    get { return proxyVersionRev_; }
    set {
      proxyVersionRev_ = value;
    }
  }

  /// <summary>Field number for the "protocol" field.</summary>
  public const int ProtocolFieldNumber = 5;
  private uint protocol_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Protocol {
    get { return protocol_; }
    set {
      protocol_ = value;
    }
  }

  /// <summary>Field number for the "use_packet_translation" field.</summary>
  public const int UsePacketTranslationFieldNumber = 6;
  private bool usePacketTranslation_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool UsePacketTranslation {
    get { return usePacketTranslation_; }
    set {
      usePacketTranslation_ = value;
    }
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 7;
  private string type_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Type {
    get { return type_; }
    set {
      type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as AuthResponce);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(AuthResponce other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Responce != other.Responce) return false;
    if (Message != other.Message) return false;
    if (ProxyVersion != other.ProxyVersion) return false;
    if (ProxyVersionRev != other.ProxyVersionRev) return false;
    if (Protocol != other.Protocol) return false;
    if (UsePacketTranslation != other.UsePacketTranslation) return false;
    if (Type != other.Type) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Responce != 0) hash ^= Responce.GetHashCode();
    if (Message.Length != 0) hash ^= Message.GetHashCode();
    if (ProxyVersion != 0) hash ^= ProxyVersion.GetHashCode();
    if (ProxyVersionRev != 0) hash ^= ProxyVersionRev.GetHashCode();
    if (Protocol != 0) hash ^= Protocol.GetHashCode();
    if (UsePacketTranslation != false) hash ^= UsePacketTranslation.GetHashCode();
    if (Type.Length != 0) hash ^= Type.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Responce != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Responce);
    }
    if (Message.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Message);
    }
    if (ProxyVersion != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(ProxyVersion);
    }
    if (ProxyVersionRev != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(ProxyVersionRev);
    }
    if (Protocol != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(Protocol);
    }
    if (UsePacketTranslation != false) {
      output.WriteRawTag(48);
      output.WriteBool(UsePacketTranslation);
    }
    if (Type.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(Type);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Responce != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Responce);
    }
    if (Message.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Message);
    }
    if (ProxyVersion != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(ProxyVersion);
    }
    if (ProxyVersionRev != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(ProxyVersionRev);
    }
    if (Protocol != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(Protocol);
    }
    if (UsePacketTranslation != false) {
      output.WriteRawTag(48);
      output.WriteBool(UsePacketTranslation);
    }
    if (Type.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(Type);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Responce != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Responce);
    }
    if (Message.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
    }
    if (ProxyVersion != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ProxyVersion);
    }
    if (ProxyVersionRev != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ProxyVersionRev);
    }
    if (Protocol != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Protocol);
    }
    if (UsePacketTranslation != false) {
      size += 1 + 1;
    }
    if (Type.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(AuthResponce other) {
    if (other == null) {
      return;
    }
    if (other.Responce != 0) {
      Responce = other.Responce;
    }
    if (other.Message.Length != 0) {
      Message = other.Message;
    }
    if (other.ProxyVersion != 0) {
      ProxyVersion = other.ProxyVersion;
    }
    if (other.ProxyVersionRev != 0) {
      ProxyVersionRev = other.ProxyVersionRev;
    }
    if (other.Protocol != 0) {
      Protocol = other.Protocol;
    }
    if (other.UsePacketTranslation != false) {
      UsePacketTranslation = other.UsePacketTranslation;
    }
    if (other.Type.Length != 0) {
      Type = other.Type;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Responce = input.ReadInt32();
          break;
        }
        case 18: {
          Message = input.ReadString();
          break;
        }
        case 24: {
          ProxyVersion = input.ReadUInt32();
          break;
        }
        case 32: {
          ProxyVersionRev = input.ReadUInt32();
          break;
        }
        case 40: {
          Protocol = input.ReadUInt32();
          break;
        }
        case 48: {
          UsePacketTranslation = input.ReadBool();
          break;
        }
        case 58: {
          Type = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Responce = input.ReadInt32();
          break;
        }
        case 18: {
          Message = input.ReadString();
          break;
        }
        case 24: {
          ProxyVersion = input.ReadUInt32();
          break;
        }
        case 32: {
          ProxyVersionRev = input.ReadUInt32();
          break;
        }
        case 40: {
          Protocol = input.ReadUInt32();
          break;
        }
        case 48: {
          UsePacketTranslation = input.ReadBool();
          break;
        }
        case 58: {
          Type = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class Data : pb::IMessage<Data>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Data> _parser = new pb::MessageParser<Data>(() => new Data());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Data> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProxyServerReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Data() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Data(Data other) : this() {
    message_ = other.message_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Data Clone() {
    return new Data(this);
  }

  /// <summary>Field number for the "message" field.</summary>
  public const int MessageFieldNumber = 1;
  private pb::ByteString message_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString Message {
    get { return message_; }
    set {
      message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Data);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Data other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Message != other.Message) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Message.Length != 0) hash ^= Message.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Message.Length != 0) {
      output.WriteRawTag(10);
      output.WriteBytes(Message);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Message.Length != 0) {
      output.WriteRawTag(10);
      output.WriteBytes(Message);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Message.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Message);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Data other) {
    if (other == null) {
      return;
    }
    if (other.Message.Length != 0) {
      Message = other.Message;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Message = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Message = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class VoxelSrvMessage : pb::IMessage<VoxelSrvMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<VoxelSrvMessage> _parser = new pb::MessageParser<VoxelSrvMessage>(() => new VoxelSrvMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<VoxelSrvMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProxyServerReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public VoxelSrvMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public VoxelSrvMessage(VoxelSrvMessage other) : this() {
    message_ = other.message_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public VoxelSrvMessage Clone() {
    return new VoxelSrvMessage(this);
  }

  /// <summary>Field number for the "message" field.</summary>
  public const int MessageFieldNumber = 1;
  private pb::ByteString message_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString Message {
    get { return message_; }
    set {
      message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as VoxelSrvMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(VoxelSrvMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Message != other.Message) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Message.Length != 0) hash ^= Message.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Message.Length != 0) {
      output.WriteRawTag(10);
      output.WriteBytes(Message);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Message.Length != 0) {
      output.WriteRawTag(10);
      output.WriteBytes(Message);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Message.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Message);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(VoxelSrvMessage other) {
    if (other == null) {
      return;
    }
    if (other.Message.Length != 0) {
      Message = other.Message;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Message = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Message = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class Disconnect : pb::IMessage<Disconnect>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Disconnect> _parser = new pb::MessageParser<Disconnect>(() => new Disconnect());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Disconnect> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProxyServerReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Disconnect() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Disconnect(Disconnect other) : this() {
    reason_ = other.reason_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Disconnect Clone() {
    return new Disconnect(this);
  }

  /// <summary>Field number for the "reason" field.</summary>
  public const int ReasonFieldNumber = 1;
  private string reason_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Reason {
    get { return reason_; }
    set {
      reason_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Disconnect);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Disconnect other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Reason != other.Reason) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Reason.Length != 0) hash ^= Reason.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Reason.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Reason);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Reason.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Reason);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Reason.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Reason);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Disconnect other) {
    if (other == null) {
      return;
    }
    if (other.Reason.Length != 0) {
      Reason = other.Reason;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Reason = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Reason = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class ProxyMessage : pb::IMessage<ProxyMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ProxyMessage> _parser = new pb::MessageParser<ProxyMessage>(() => new ProxyMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ProxyMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProxyServerReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProxyMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProxyMessage(ProxyMessage other) : this() {
    message_ = other.message_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProxyMessage Clone() {
    return new ProxyMessage(this);
  }

  /// <summary>Field number for the "message" field.</summary>
  public const int MessageFieldNumber = 1;
  private pb::ByteString message_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString Message {
    get { return message_; }
    set {
      message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ProxyMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ProxyMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Message != other.Message) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Message.Length != 0) hash ^= Message.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Message.Length != 0) {
      output.WriteRawTag(10);
      output.WriteBytes(Message);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Message.Length != 0) {
      output.WriteRawTag(10);
      output.WriteBytes(Message);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Message.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Message);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ProxyMessage other) {
    if (other == null) {
      return;
    }
    if (other.Message.Length != 0) {
      Message = other.Message;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Message = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Message = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
