// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/proxy-server.proto

public final class ProxyServer {
  private ProxyServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ProxyInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProxyInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>uint32 proxy_protocol = 2;</code>
     * @return The proxyProtocol.
     */
    int getProxyProtocol();

    /**
     * <code>uint32 online_players = 3;</code>
     * @return The onlinePlayers.
     */
    int getOnlinePlayers();

    /**
     * <code>uint32 max_players = 4;</code>
     * @return The maxPlayers.
     */
    int getMaxPlayers();

    /**
     * <code>string motd = 5;</code>
     * @return The motd.
     */
    java.lang.String getMotd();
    /**
     * <code>string motd = 5;</code>
     * @return The bytes for motd.
     */
    com.google.protobuf.ByteString
        getMotdBytes();

    /**
     * <code>string software = 6;</code>
     * @return The software.
     */
    java.lang.String getSoftware();
    /**
     * <code>string software = 6;</code>
     * @return The bytes for software.
     */
    com.google.protobuf.ByteString
        getSoftwareBytes();

    /**
     * <code>bool auth = 7;</code>
     * @return The auth.
     */
    boolean getAuth();

    /**
     * <code>string secret = 8;</code>
     * @return The secret.
     */
    java.lang.String getSecret();
    /**
     * <code>string secret = 8;</code>
     * @return The bytes for secret.
     */
    com.google.protobuf.ByteString
        getSecretBytes();

    /**
     * <code>bool is_proxy = 9;</code>
     * @return The isProxy.
     */
    boolean getIsProxy();
  }
  /**
   * Protobuf type {@code ProxyInfo}
   */
  public  static final class ProxyInfo extends
      com.google.protobuf.GeneratedMessageLite<
          ProxyInfo, ProxyInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:ProxyInfo)
      ProxyInfoOrBuilder {
    private ProxyInfo() {
      name_ = "";
      motd_ = "";
      software_ = "";
      secret_ = "";
    }
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.String name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     */
    private void setName(
        java.lang.String value) {
      value.getClass();
  
      name_ = value;
    }
    /**
     * <code>string name = 1;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      name_ = value.toStringUtf8();
      
    }

    public static final int PROXY_PROTOCOL_FIELD_NUMBER = 2;
    private int proxyProtocol_;
    /**
     * <code>uint32 proxy_protocol = 2;</code>
     * @return The proxyProtocol.
     */
    @java.lang.Override
    public int getProxyProtocol() {
      return proxyProtocol_;
    }
    /**
     * <code>uint32 proxy_protocol = 2;</code>
     * @param value The proxyProtocol to set.
     */
    private void setProxyProtocol(int value) {
      
      proxyProtocol_ = value;
    }
    /**
     * <code>uint32 proxy_protocol = 2;</code>
     */
    private void clearProxyProtocol() {
      
      proxyProtocol_ = 0;
    }

    public static final int ONLINE_PLAYERS_FIELD_NUMBER = 3;
    private int onlinePlayers_;
    /**
     * <code>uint32 online_players = 3;</code>
     * @return The onlinePlayers.
     */
    @java.lang.Override
    public int getOnlinePlayers() {
      return onlinePlayers_;
    }
    /**
     * <code>uint32 online_players = 3;</code>
     * @param value The onlinePlayers to set.
     */
    private void setOnlinePlayers(int value) {
      
      onlinePlayers_ = value;
    }
    /**
     * <code>uint32 online_players = 3;</code>
     */
    private void clearOnlinePlayers() {
      
      onlinePlayers_ = 0;
    }

    public static final int MAX_PLAYERS_FIELD_NUMBER = 4;
    private int maxPlayers_;
    /**
     * <code>uint32 max_players = 4;</code>
     * @return The maxPlayers.
     */
    @java.lang.Override
    public int getMaxPlayers() {
      return maxPlayers_;
    }
    /**
     * <code>uint32 max_players = 4;</code>
     * @param value The maxPlayers to set.
     */
    private void setMaxPlayers(int value) {
      
      maxPlayers_ = value;
    }
    /**
     * <code>uint32 max_players = 4;</code>
     */
    private void clearMaxPlayers() {
      
      maxPlayers_ = 0;
    }

    public static final int MOTD_FIELD_NUMBER = 5;
    private java.lang.String motd_;
    /**
     * <code>string motd = 5;</code>
     * @return The motd.
     */
    @java.lang.Override
    public java.lang.String getMotd() {
      return motd_;
    }
    /**
     * <code>string motd = 5;</code>
     * @return The bytes for motd.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMotdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(motd_);
    }
    /**
     * <code>string motd = 5;</code>
     * @param value The motd to set.
     */
    private void setMotd(
        java.lang.String value) {
      value.getClass();
  
      motd_ = value;
    }
    /**
     * <code>string motd = 5;</code>
     */
    private void clearMotd() {
      
      motd_ = getDefaultInstance().getMotd();
    }
    /**
     * <code>string motd = 5;</code>
     * @param value The bytes for motd to set.
     */
    private void setMotdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      motd_ = value.toStringUtf8();
      
    }

    public static final int SOFTWARE_FIELD_NUMBER = 6;
    private java.lang.String software_;
    /**
     * <code>string software = 6;</code>
     * @return The software.
     */
    @java.lang.Override
    public java.lang.String getSoftware() {
      return software_;
    }
    /**
     * <code>string software = 6;</code>
     * @return The bytes for software.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSoftwareBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(software_);
    }
    /**
     * <code>string software = 6;</code>
     * @param value The software to set.
     */
    private void setSoftware(
        java.lang.String value) {
      value.getClass();
  
      software_ = value;
    }
    /**
     * <code>string software = 6;</code>
     */
    private void clearSoftware() {
      
      software_ = getDefaultInstance().getSoftware();
    }
    /**
     * <code>string software = 6;</code>
     * @param value The bytes for software to set.
     */
    private void setSoftwareBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      software_ = value.toStringUtf8();
      
    }

    public static final int AUTH_FIELD_NUMBER = 7;
    private boolean auth_;
    /**
     * <code>bool auth = 7;</code>
     * @return The auth.
     */
    @java.lang.Override
    public boolean getAuth() {
      return auth_;
    }
    /**
     * <code>bool auth = 7;</code>
     * @param value The auth to set.
     */
    private void setAuth(boolean value) {
      
      auth_ = value;
    }
    /**
     * <code>bool auth = 7;</code>
     */
    private void clearAuth() {
      
      auth_ = false;
    }

    public static final int SECRET_FIELD_NUMBER = 8;
    private java.lang.String secret_;
    /**
     * <code>string secret = 8;</code>
     * @return The secret.
     */
    @java.lang.Override
    public java.lang.String getSecret() {
      return secret_;
    }
    /**
     * <code>string secret = 8;</code>
     * @return The bytes for secret.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSecretBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(secret_);
    }
    /**
     * <code>string secret = 8;</code>
     * @param value The secret to set.
     */
    private void setSecret(
        java.lang.String value) {
      value.getClass();
  
      secret_ = value;
    }
    /**
     * <code>string secret = 8;</code>
     */
    private void clearSecret() {
      
      secret_ = getDefaultInstance().getSecret();
    }
    /**
     * <code>string secret = 8;</code>
     * @param value The bytes for secret to set.
     */
    private void setSecretBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      secret_ = value.toStringUtf8();
      
    }

    public static final int IS_PROXY_FIELD_NUMBER = 9;
    private boolean isProxy_;
    /**
     * <code>bool is_proxy = 9;</code>
     * @return The isProxy.
     */
    @java.lang.Override
    public boolean getIsProxy() {
      return isProxy_;
    }
    /**
     * <code>bool is_proxy = 9;</code>
     * @param value The isProxy to set.
     */
    private void setIsProxy(boolean value) {
      
      isProxy_ = value;
    }
    /**
     * <code>bool is_proxy = 9;</code>
     */
    private void clearIsProxy() {
      
      isProxy_ = false;
    }

    public static ProxyServer.ProxyInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProxyServer.ProxyInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProxyServer.ProxyInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProxyServer.ProxyInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProxyServer.ProxyInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProxyServer.ProxyInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProxyServer.ProxyInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ProxyServer.ProxyInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ProxyServer.ProxyInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ProxyServer.ProxyInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ProxyServer.ProxyInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ProxyServer.ProxyInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ProxyServer.ProxyInfo prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code ProxyInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ProxyServer.ProxyInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:ProxyInfo)
        ProxyServer.ProxyInfoOrBuilder {
      // Construct using ProxyServer.ProxyInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      @java.lang.Override
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>uint32 proxy_protocol = 2;</code>
       * @return The proxyProtocol.
       */
      @java.lang.Override
      public int getProxyProtocol() {
        return instance.getProxyProtocol();
      }
      /**
       * <code>uint32 proxy_protocol = 2;</code>
       * @param value The proxyProtocol to set.
       * @return This builder for chaining.
       */
      public Builder setProxyProtocol(int value) {
        copyOnWrite();
        instance.setProxyProtocol(value);
        return this;
      }
      /**
       * <code>uint32 proxy_protocol = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProxyProtocol() {
        copyOnWrite();
        instance.clearProxyProtocol();
        return this;
      }

      /**
       * <code>uint32 online_players = 3;</code>
       * @return The onlinePlayers.
       */
      @java.lang.Override
      public int getOnlinePlayers() {
        return instance.getOnlinePlayers();
      }
      /**
       * <code>uint32 online_players = 3;</code>
       * @param value The onlinePlayers to set.
       * @return This builder for chaining.
       */
      public Builder setOnlinePlayers(int value) {
        copyOnWrite();
        instance.setOnlinePlayers(value);
        return this;
      }
      /**
       * <code>uint32 online_players = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOnlinePlayers() {
        copyOnWrite();
        instance.clearOnlinePlayers();
        return this;
      }

      /**
       * <code>uint32 max_players = 4;</code>
       * @return The maxPlayers.
       */
      @java.lang.Override
      public int getMaxPlayers() {
        return instance.getMaxPlayers();
      }
      /**
       * <code>uint32 max_players = 4;</code>
       * @param value The maxPlayers to set.
       * @return This builder for chaining.
       */
      public Builder setMaxPlayers(int value) {
        copyOnWrite();
        instance.setMaxPlayers(value);
        return this;
      }
      /**
       * <code>uint32 max_players = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxPlayers() {
        copyOnWrite();
        instance.clearMaxPlayers();
        return this;
      }

      /**
       * <code>string motd = 5;</code>
       * @return The motd.
       */
      @java.lang.Override
      public java.lang.String getMotd() {
        return instance.getMotd();
      }
      /**
       * <code>string motd = 5;</code>
       * @return The bytes for motd.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMotdBytes() {
        return instance.getMotdBytes();
      }
      /**
       * <code>string motd = 5;</code>
       * @param value The motd to set.
       * @return This builder for chaining.
       */
      public Builder setMotd(
          java.lang.String value) {
        copyOnWrite();
        instance.setMotd(value);
        return this;
      }
      /**
       * <code>string motd = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMotd() {
        copyOnWrite();
        instance.clearMotd();
        return this;
      }
      /**
       * <code>string motd = 5;</code>
       * @param value The bytes for motd to set.
       * @return This builder for chaining.
       */
      public Builder setMotdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMotdBytes(value);
        return this;
      }

      /**
       * <code>string software = 6;</code>
       * @return The software.
       */
      @java.lang.Override
      public java.lang.String getSoftware() {
        return instance.getSoftware();
      }
      /**
       * <code>string software = 6;</code>
       * @return The bytes for software.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSoftwareBytes() {
        return instance.getSoftwareBytes();
      }
      /**
       * <code>string software = 6;</code>
       * @param value The software to set.
       * @return This builder for chaining.
       */
      public Builder setSoftware(
          java.lang.String value) {
        copyOnWrite();
        instance.setSoftware(value);
        return this;
      }
      /**
       * <code>string software = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSoftware() {
        copyOnWrite();
        instance.clearSoftware();
        return this;
      }
      /**
       * <code>string software = 6;</code>
       * @param value The bytes for software to set.
       * @return This builder for chaining.
       */
      public Builder setSoftwareBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSoftwareBytes(value);
        return this;
      }

      /**
       * <code>bool auth = 7;</code>
       * @return The auth.
       */
      @java.lang.Override
      public boolean getAuth() {
        return instance.getAuth();
      }
      /**
       * <code>bool auth = 7;</code>
       * @param value The auth to set.
       * @return This builder for chaining.
       */
      public Builder setAuth(boolean value) {
        copyOnWrite();
        instance.setAuth(value);
        return this;
      }
      /**
       * <code>bool auth = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuth() {
        copyOnWrite();
        instance.clearAuth();
        return this;
      }

      /**
       * <code>string secret = 8;</code>
       * @return The secret.
       */
      @java.lang.Override
      public java.lang.String getSecret() {
        return instance.getSecret();
      }
      /**
       * <code>string secret = 8;</code>
       * @return The bytes for secret.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSecretBytes() {
        return instance.getSecretBytes();
      }
      /**
       * <code>string secret = 8;</code>
       * @param value The secret to set.
       * @return This builder for chaining.
       */
      public Builder setSecret(
          java.lang.String value) {
        copyOnWrite();
        instance.setSecret(value);
        return this;
      }
      /**
       * <code>string secret = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecret() {
        copyOnWrite();
        instance.clearSecret();
        return this;
      }
      /**
       * <code>string secret = 8;</code>
       * @param value The bytes for secret to set.
       * @return This builder for chaining.
       */
      public Builder setSecretBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSecretBytes(value);
        return this;
      }

      /**
       * <code>bool is_proxy = 9;</code>
       * @return The isProxy.
       */
      @java.lang.Override
      public boolean getIsProxy() {
        return instance.getIsProxy();
      }
      /**
       * <code>bool is_proxy = 9;</code>
       * @param value The isProxy to set.
       * @return This builder for chaining.
       */
      public Builder setIsProxy(boolean value) {
        copyOnWrite();
        instance.setIsProxy(value);
        return this;
      }
      /**
       * <code>bool is_proxy = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsProxy() {
        copyOnWrite();
        instance.clearIsProxy();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProxyInfo)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ProxyServer.ProxyInfo();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "name_",
              "proxyProtocol_",
              "onlinePlayers_",
              "maxPlayers_",
              "motd_",
              "software_",
              "auth_",
              "secret_",
              "isProxy_",
            };
            java.lang.String info =
                "\u0000\t\u0000\u0000\u0001\t\t\u0000\u0000\u0000\u0001\u0208\u0002\u000b\u0003\u000b" +
                "\u0004\u000b\u0005\u0208\u0006\u0208\u0007\u0007\b\u0208\t\u0007";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ProxyServer.ProxyInfo> parser = PARSER;
          if (parser == null) {
            synchronized (ProxyServer.ProxyInfo.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<ProxyServer.ProxyInfo>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:ProxyInfo)
    private static final ProxyServer.ProxyInfo DEFAULT_INSTANCE;
    static {
      ProxyInfo defaultInstance = new ProxyInfo();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ProxyInfo.class, defaultInstance);
    }

    public static ProxyServer.ProxyInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ProxyInfo> PARSER;

    public static com.google.protobuf.Parser<ProxyInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface AuthResponceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AuthResponce)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 responce = 1;</code>
     * @return The responce.
     */
    int getResponce();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>uint32 proxy_version = 3;</code>
     * @return The proxyVersion.
     */
    int getProxyVersion();

    /**
     * <code>uint32 proxy_version_rev = 4;</code>
     * @return The proxyVersionRev.
     */
    int getProxyVersionRev();

    /**
     * <code>uint32 protocol = 5;</code>
     * @return The protocol.
     */
    int getProtocol();

    /**
     * <code>bool use_packet_translation = 6;</code>
     * @return The usePacketTranslation.
     */
    boolean getUsePacketTranslation();

    /**
     * <code>string type = 7;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <code>string type = 7;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * Protobuf type {@code AuthResponce}
   */
  public  static final class AuthResponce extends
      com.google.protobuf.GeneratedMessageLite<
          AuthResponce, AuthResponce.Builder> implements
      // @@protoc_insertion_point(message_implements:AuthResponce)
      AuthResponceOrBuilder {
    private AuthResponce() {
      message_ = "";
      type_ = "";
    }
    public static final int RESPONCE_FIELD_NUMBER = 1;
    private int responce_;
    /**
     * <code>int32 responce = 1;</code>
     * @return The responce.
     */
    @java.lang.Override
    public int getResponce() {
      return responce_;
    }
    /**
     * <code>int32 responce = 1;</code>
     * @param value The responce to set.
     */
    private void setResponce(int value) {
      
      responce_ = value;
    }
    /**
     * <code>int32 responce = 1;</code>
     */
    private void clearResponce() {
      
      responce_ = 0;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.lang.String message_;
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      return message_;
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(message_);
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     */
    private void setMessage(
        java.lang.String value) {
      value.getClass();
  
      message_ = value;
    }
    /**
     * <code>string message = 2;</code>
     */
    private void clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     */
    private void setMessageBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      message_ = value.toStringUtf8();
      
    }

    public static final int PROXY_VERSION_FIELD_NUMBER = 3;
    private int proxyVersion_;
    /**
     * <code>uint32 proxy_version = 3;</code>
     * @return The proxyVersion.
     */
    @java.lang.Override
    public int getProxyVersion() {
      return proxyVersion_;
    }
    /**
     * <code>uint32 proxy_version = 3;</code>
     * @param value The proxyVersion to set.
     */
    private void setProxyVersion(int value) {
      
      proxyVersion_ = value;
    }
    /**
     * <code>uint32 proxy_version = 3;</code>
     */
    private void clearProxyVersion() {
      
      proxyVersion_ = 0;
    }

    public static final int PROXY_VERSION_REV_FIELD_NUMBER = 4;
    private int proxyVersionRev_;
    /**
     * <code>uint32 proxy_version_rev = 4;</code>
     * @return The proxyVersionRev.
     */
    @java.lang.Override
    public int getProxyVersionRev() {
      return proxyVersionRev_;
    }
    /**
     * <code>uint32 proxy_version_rev = 4;</code>
     * @param value The proxyVersionRev to set.
     */
    private void setProxyVersionRev(int value) {
      
      proxyVersionRev_ = value;
    }
    /**
     * <code>uint32 proxy_version_rev = 4;</code>
     */
    private void clearProxyVersionRev() {
      
      proxyVersionRev_ = 0;
    }

    public static final int PROTOCOL_FIELD_NUMBER = 5;
    private int protocol_;
    /**
     * <code>uint32 protocol = 5;</code>
     * @return The protocol.
     */
    @java.lang.Override
    public int getProtocol() {
      return protocol_;
    }
    /**
     * <code>uint32 protocol = 5;</code>
     * @param value The protocol to set.
     */
    private void setProtocol(int value) {
      
      protocol_ = value;
    }
    /**
     * <code>uint32 protocol = 5;</code>
     */
    private void clearProtocol() {
      
      protocol_ = 0;
    }

    public static final int USE_PACKET_TRANSLATION_FIELD_NUMBER = 6;
    private boolean usePacketTranslation_;
    /**
     * <code>bool use_packet_translation = 6;</code>
     * @return The usePacketTranslation.
     */
    @java.lang.Override
    public boolean getUsePacketTranslation() {
      return usePacketTranslation_;
    }
    /**
     * <code>bool use_packet_translation = 6;</code>
     * @param value The usePacketTranslation to set.
     */
    private void setUsePacketTranslation(boolean value) {
      
      usePacketTranslation_ = value;
    }
    /**
     * <code>bool use_packet_translation = 6;</code>
     */
    private void clearUsePacketTranslation() {
      
      usePacketTranslation_ = false;
    }

    public static final int TYPE_FIELD_NUMBER = 7;
    private java.lang.String type_;
    /**
     * <code>string type = 7;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      return type_;
    }
    /**
     * <code>string type = 7;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(type_);
    }
    /**
     * <code>string type = 7;</code>
     * @param value The type to set.
     */
    private void setType(
        java.lang.String value) {
      value.getClass();
  
      type_ = value;
    }
    /**
     * <code>string type = 7;</code>
     */
    private void clearType() {
      
      type_ = getDefaultInstance().getType();
    }
    /**
     * <code>string type = 7;</code>
     * @param value The bytes for type to set.
     */
    private void setTypeBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      type_ = value.toStringUtf8();
      
    }

    public static ProxyServer.AuthResponce parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProxyServer.AuthResponce parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProxyServer.AuthResponce parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProxyServer.AuthResponce parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProxyServer.AuthResponce parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProxyServer.AuthResponce parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProxyServer.AuthResponce parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ProxyServer.AuthResponce parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ProxyServer.AuthResponce parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ProxyServer.AuthResponce parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ProxyServer.AuthResponce parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ProxyServer.AuthResponce parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ProxyServer.AuthResponce prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code AuthResponce}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ProxyServer.AuthResponce, Builder> implements
        // @@protoc_insertion_point(builder_implements:AuthResponce)
        ProxyServer.AuthResponceOrBuilder {
      // Construct using ProxyServer.AuthResponce.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 responce = 1;</code>
       * @return The responce.
       */
      @java.lang.Override
      public int getResponce() {
        return instance.getResponce();
      }
      /**
       * <code>int32 responce = 1;</code>
       * @param value The responce to set.
       * @return This builder for chaining.
       */
      public Builder setResponce(int value) {
        copyOnWrite();
        instance.setResponce(value);
        return this;
      }
      /**
       * <code>int32 responce = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponce() {
        copyOnWrite();
        instance.clearResponce();
        return this;
      }

      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      @java.lang.Override
      public java.lang.String getMessage() {
        return instance.getMessage();
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMessageBytes() {
        return instance.getMessageBytes();
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        copyOnWrite();
        instance.setMessage(value);
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        copyOnWrite();
        instance.clearMessage();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMessageBytes(value);
        return this;
      }

      /**
       * <code>uint32 proxy_version = 3;</code>
       * @return The proxyVersion.
       */
      @java.lang.Override
      public int getProxyVersion() {
        return instance.getProxyVersion();
      }
      /**
       * <code>uint32 proxy_version = 3;</code>
       * @param value The proxyVersion to set.
       * @return This builder for chaining.
       */
      public Builder setProxyVersion(int value) {
        copyOnWrite();
        instance.setProxyVersion(value);
        return this;
      }
      /**
       * <code>uint32 proxy_version = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearProxyVersion() {
        copyOnWrite();
        instance.clearProxyVersion();
        return this;
      }

      /**
       * <code>uint32 proxy_version_rev = 4;</code>
       * @return The proxyVersionRev.
       */
      @java.lang.Override
      public int getProxyVersionRev() {
        return instance.getProxyVersionRev();
      }
      /**
       * <code>uint32 proxy_version_rev = 4;</code>
       * @param value The proxyVersionRev to set.
       * @return This builder for chaining.
       */
      public Builder setProxyVersionRev(int value) {
        copyOnWrite();
        instance.setProxyVersionRev(value);
        return this;
      }
      /**
       * <code>uint32 proxy_version_rev = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearProxyVersionRev() {
        copyOnWrite();
        instance.clearProxyVersionRev();
        return this;
      }

      /**
       * <code>uint32 protocol = 5;</code>
       * @return The protocol.
       */
      @java.lang.Override
      public int getProtocol() {
        return instance.getProtocol();
      }
      /**
       * <code>uint32 protocol = 5;</code>
       * @param value The protocol to set.
       * @return This builder for chaining.
       */
      public Builder setProtocol(int value) {
        copyOnWrite();
        instance.setProtocol(value);
        return this;
      }
      /**
       * <code>uint32 protocol = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearProtocol() {
        copyOnWrite();
        instance.clearProtocol();
        return this;
      }

      /**
       * <code>bool use_packet_translation = 6;</code>
       * @return The usePacketTranslation.
       */
      @java.lang.Override
      public boolean getUsePacketTranslation() {
        return instance.getUsePacketTranslation();
      }
      /**
       * <code>bool use_packet_translation = 6;</code>
       * @param value The usePacketTranslation to set.
       * @return This builder for chaining.
       */
      public Builder setUsePacketTranslation(boolean value) {
        copyOnWrite();
        instance.setUsePacketTranslation(value);
        return this;
      }
      /**
       * <code>bool use_packet_translation = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsePacketTranslation() {
        copyOnWrite();
        instance.clearUsePacketTranslation();
        return this;
      }

      /**
       * <code>string type = 7;</code>
       * @return The type.
       */
      @java.lang.Override
      public java.lang.String getType() {
        return instance.getType();
      }
      /**
       * <code>string type = 7;</code>
       * @return The bytes for type.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTypeBytes() {
        return instance.getTypeBytes();
      }
      /**
       * <code>string type = 7;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>string type = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }
      /**
       * <code>string type = 7;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTypeBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AuthResponce)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ProxyServer.AuthResponce();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "responce_",
              "message_",
              "proxyVersion_",
              "proxyVersionRev_",
              "protocol_",
              "usePacketTranslation_",
              "type_",
            };
            java.lang.String info =
                "\u0000\u0007\u0000\u0000\u0001\u0007\u0007\u0000\u0000\u0000\u0001\u0004\u0002\u0208" +
                "\u0003\u000b\u0004\u000b\u0005\u000b\u0006\u0007\u0007\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ProxyServer.AuthResponce> parser = PARSER;
          if (parser == null) {
            synchronized (ProxyServer.AuthResponce.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<ProxyServer.AuthResponce>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:AuthResponce)
    private static final ProxyServer.AuthResponce DEFAULT_INSTANCE;
    static {
      AuthResponce defaultInstance = new AuthResponce();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        AuthResponce.class, defaultInstance);
    }

    public static ProxyServer.AuthResponce getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AuthResponce> PARSER;

    public static com.google.protobuf.Parser<AuthResponce> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Data)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bytes message = 1;</code>
     * @return The message.
     */
    com.google.protobuf.ByteString getMessage();
  }
  /**
   * Protobuf type {@code Data}
   */
  public  static final class Data extends
      com.google.protobuf.GeneratedMessageLite<
          Data, Data.Builder> implements
      // @@protoc_insertion_point(message_implements:Data)
      DataOrBuilder {
    private Data() {
      message_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString message_;
    /**
     * <code>bytes message = 1;</code>
     * @return The message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMessage() {
      return message_;
    }
    /**
     * <code>bytes message = 1;</code>
     * @param value The message to set.
     */
    private void setMessage(com.google.protobuf.ByteString value) {
      value.getClass();
  
      message_ = value;
    }
    /**
     * <code>bytes message = 1;</code>
     */
    private void clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
    }

    public static ProxyServer.Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProxyServer.Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProxyServer.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProxyServer.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProxyServer.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProxyServer.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProxyServer.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ProxyServer.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ProxyServer.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ProxyServer.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ProxyServer.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ProxyServer.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ProxyServer.Data prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ProxyServer.Data, Builder> implements
        // @@protoc_insertion_point(builder_implements:Data)
        ProxyServer.DataOrBuilder {
      // Construct using ProxyServer.Data.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bytes message = 1;</code>
       * @return The message.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getMessage() {
        return instance.getMessage();
      }
      /**
       * <code>bytes message = 1;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMessage(value);
        return this;
      }
      /**
       * <code>bytes message = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        copyOnWrite();
        instance.clearMessage();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Data)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ProxyServer.Data();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "message_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ProxyServer.Data> parser = PARSER;
          if (parser == null) {
            synchronized (ProxyServer.Data.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<ProxyServer.Data>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Data)
    private static final ProxyServer.Data DEFAULT_INSTANCE;
    static {
      Data defaultInstance = new Data();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Data.class, defaultInstance);
    }

    public static ProxyServer.Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Data> PARSER;

    public static com.google.protobuf.Parser<Data> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface VoxelSrvMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VoxelSrvMessage)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bytes message = 1;</code>
     * @return The message.
     */
    com.google.protobuf.ByteString getMessage();
  }
  /**
   * Protobuf type {@code VoxelSrvMessage}
   */
  public  static final class VoxelSrvMessage extends
      com.google.protobuf.GeneratedMessageLite<
          VoxelSrvMessage, VoxelSrvMessage.Builder> implements
      // @@protoc_insertion_point(message_implements:VoxelSrvMessage)
      VoxelSrvMessageOrBuilder {
    private VoxelSrvMessage() {
      message_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString message_;
    /**
     * <code>bytes message = 1;</code>
     * @return The message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMessage() {
      return message_;
    }
    /**
     * <code>bytes message = 1;</code>
     * @param value The message to set.
     */
    private void setMessage(com.google.protobuf.ByteString value) {
      value.getClass();
  
      message_ = value;
    }
    /**
     * <code>bytes message = 1;</code>
     */
    private void clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
    }

    public static ProxyServer.VoxelSrvMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProxyServer.VoxelSrvMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProxyServer.VoxelSrvMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProxyServer.VoxelSrvMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProxyServer.VoxelSrvMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProxyServer.VoxelSrvMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProxyServer.VoxelSrvMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ProxyServer.VoxelSrvMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ProxyServer.VoxelSrvMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ProxyServer.VoxelSrvMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ProxyServer.VoxelSrvMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ProxyServer.VoxelSrvMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ProxyServer.VoxelSrvMessage prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code VoxelSrvMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ProxyServer.VoxelSrvMessage, Builder> implements
        // @@protoc_insertion_point(builder_implements:VoxelSrvMessage)
        ProxyServer.VoxelSrvMessageOrBuilder {
      // Construct using ProxyServer.VoxelSrvMessage.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bytes message = 1;</code>
       * @return The message.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getMessage() {
        return instance.getMessage();
      }
      /**
       * <code>bytes message = 1;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMessage(value);
        return this;
      }
      /**
       * <code>bytes message = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        copyOnWrite();
        instance.clearMessage();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:VoxelSrvMessage)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ProxyServer.VoxelSrvMessage();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "message_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ProxyServer.VoxelSrvMessage> parser = PARSER;
          if (parser == null) {
            synchronized (ProxyServer.VoxelSrvMessage.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<ProxyServer.VoxelSrvMessage>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:VoxelSrvMessage)
    private static final ProxyServer.VoxelSrvMessage DEFAULT_INSTANCE;
    static {
      VoxelSrvMessage defaultInstance = new VoxelSrvMessage();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        VoxelSrvMessage.class, defaultInstance);
    }

    public static ProxyServer.VoxelSrvMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<VoxelSrvMessage> PARSER;

    public static com.google.protobuf.Parser<VoxelSrvMessage> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface DisconnectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Disconnect)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string reason = 1;</code>
     * @return The reason.
     */
    java.lang.String getReason();
    /**
     * <code>string reason = 1;</code>
     * @return The bytes for reason.
     */
    com.google.protobuf.ByteString
        getReasonBytes();
  }
  /**
   * Protobuf type {@code Disconnect}
   */
  public  static final class Disconnect extends
      com.google.protobuf.GeneratedMessageLite<
          Disconnect, Disconnect.Builder> implements
      // @@protoc_insertion_point(message_implements:Disconnect)
      DisconnectOrBuilder {
    private Disconnect() {
      reason_ = "";
    }
    public static final int REASON_FIELD_NUMBER = 1;
    private java.lang.String reason_;
    /**
     * <code>string reason = 1;</code>
     * @return The reason.
     */
    @java.lang.Override
    public java.lang.String getReason() {
      return reason_;
    }
    /**
     * <code>string reason = 1;</code>
     * @return The bytes for reason.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReasonBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(reason_);
    }
    /**
     * <code>string reason = 1;</code>
     * @param value The reason to set.
     */
    private void setReason(
        java.lang.String value) {
      value.getClass();
  
      reason_ = value;
    }
    /**
     * <code>string reason = 1;</code>
     */
    private void clearReason() {
      
      reason_ = getDefaultInstance().getReason();
    }
    /**
     * <code>string reason = 1;</code>
     * @param value The bytes for reason to set.
     */
    private void setReasonBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      reason_ = value.toStringUtf8();
      
    }

    public static ProxyServer.Disconnect parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProxyServer.Disconnect parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProxyServer.Disconnect parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProxyServer.Disconnect parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProxyServer.Disconnect parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProxyServer.Disconnect parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProxyServer.Disconnect parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ProxyServer.Disconnect parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ProxyServer.Disconnect parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ProxyServer.Disconnect parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ProxyServer.Disconnect parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ProxyServer.Disconnect parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ProxyServer.Disconnect prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code Disconnect}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ProxyServer.Disconnect, Builder> implements
        // @@protoc_insertion_point(builder_implements:Disconnect)
        ProxyServer.DisconnectOrBuilder {
      // Construct using ProxyServer.Disconnect.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string reason = 1;</code>
       * @return The reason.
       */
      @java.lang.Override
      public java.lang.String getReason() {
        return instance.getReason();
      }
      /**
       * <code>string reason = 1;</code>
       * @return The bytes for reason.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getReasonBytes() {
        return instance.getReasonBytes();
      }
      /**
       * <code>string reason = 1;</code>
       * @param value The reason to set.
       * @return This builder for chaining.
       */
      public Builder setReason(
          java.lang.String value) {
        copyOnWrite();
        instance.setReason(value);
        return this;
      }
      /**
       * <code>string reason = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearReason() {
        copyOnWrite();
        instance.clearReason();
        return this;
      }
      /**
       * <code>string reason = 1;</code>
       * @param value The bytes for reason to set.
       * @return This builder for chaining.
       */
      public Builder setReasonBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setReasonBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Disconnect)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ProxyServer.Disconnect();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "reason_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ProxyServer.Disconnect> parser = PARSER;
          if (parser == null) {
            synchronized (ProxyServer.Disconnect.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<ProxyServer.Disconnect>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Disconnect)
    private static final ProxyServer.Disconnect DEFAULT_INSTANCE;
    static {
      Disconnect defaultInstance = new Disconnect();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Disconnect.class, defaultInstance);
    }

    public static ProxyServer.Disconnect getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Disconnect> PARSER;

    public static com.google.protobuf.Parser<Disconnect> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ProxyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProxyMessage)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bytes message = 1;</code>
     * @return The message.
     */
    com.google.protobuf.ByteString getMessage();
  }
  /**
   * Protobuf type {@code ProxyMessage}
   */
  public  static final class ProxyMessage extends
      com.google.protobuf.GeneratedMessageLite<
          ProxyMessage, ProxyMessage.Builder> implements
      // @@protoc_insertion_point(message_implements:ProxyMessage)
      ProxyMessageOrBuilder {
    private ProxyMessage() {
      message_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString message_;
    /**
     * <code>bytes message = 1;</code>
     * @return The message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMessage() {
      return message_;
    }
    /**
     * <code>bytes message = 1;</code>
     * @param value The message to set.
     */
    private void setMessage(com.google.protobuf.ByteString value) {
      value.getClass();
  
      message_ = value;
    }
    /**
     * <code>bytes message = 1;</code>
     */
    private void clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
    }

    public static ProxyServer.ProxyMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProxyServer.ProxyMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProxyServer.ProxyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProxyServer.ProxyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProxyServer.ProxyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ProxyServer.ProxyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ProxyServer.ProxyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ProxyServer.ProxyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ProxyServer.ProxyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ProxyServer.ProxyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ProxyServer.ProxyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ProxyServer.ProxyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ProxyServer.ProxyMessage prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code ProxyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ProxyServer.ProxyMessage, Builder> implements
        // @@protoc_insertion_point(builder_implements:ProxyMessage)
        ProxyServer.ProxyMessageOrBuilder {
      // Construct using ProxyServer.ProxyMessage.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bytes message = 1;</code>
       * @return The message.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getMessage() {
        return instance.getMessage();
      }
      /**
       * <code>bytes message = 1;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMessage(value);
        return this;
      }
      /**
       * <code>bytes message = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        copyOnWrite();
        instance.clearMessage();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProxyMessage)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ProxyServer.ProxyMessage();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "message_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ProxyServer.ProxyMessage> parser = PARSER;
          if (parser == null) {
            synchronized (ProxyServer.ProxyMessage.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<ProxyServer.ProxyMessage>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:ProxyMessage)
    private static final ProxyServer.ProxyMessage DEFAULT_INSTANCE;
    static {
      ProxyMessage defaultInstance = new ProxyMessage();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ProxyMessage.class, defaultInstance);
    }

    public static ProxyServer.ProxyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ProxyMessage> PARSER;

    public static com.google.protobuf.Parser<ProxyMessage> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
